version: '3.7'

services:
  eureka:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8761:8761
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/log/moa-gateway:/var/log/moa-gateway

networks:
  default:
    external:
      name: bside-moa

